name: bottom_aligned_button
description: A Flutter package to place button at the bottom
version: 0.0.3
repository: https://github.com/mishkov/bottom_aligned_button

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
